name: Run Jest Tests on PR

on:
  pull_request_target:
    types:
      - opened
      - synchronize

jobs:
  test:
    name: Run Jest Tests
    runs-on: ubuntu-latest
    permissions: 
      pull-requests: write
      contents: read
      issues: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Run Jest Tests
        id: jest
        run: |
          npm test -- --json --outputFile=jest-results.json || echo "TESTS_FAILED=true" >> $GITHUB_ENV

      - name: Read Jest Results
        id: results
        run: |
          if [ -z "$TESTS_FAILED" ]; then
            TESTS_FAILED=false
          fi

          if [ "$TESTS_FAILED" = "true" ]; then
            TESTS_PASSED=false
            echo "TESTS_PASSED=false" >> $GITHUB_ENV
            FAILED_TESTS=$(jq -r '[.testResults[] | select(.status == "failed") | .name] | map(split("/") | last) | join("\n")' jest-results.json)
            echo "FAILED_TESTS<<EOF" >> $GITHUB_ENV
            echo "$FAILED_TESTS" | sed 's/^/    /' >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
          else
            TESTS_PASSED=true
            echo "TESTS_PASSED=true" >> $GITHUB_ENV
            echo "FAILED_TESTS=None" >> $GITHUB_ENV
          fi

          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_OUTPUT

      - name: Post PR Comment using gh CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          COMMENT_BODY=""
          if [ "$TESTS_PASSED" = "true" ]; then
            COMMENT_BODY="✅ All Jest tests passed! This PR is ready to merge."
          else
            COMMENT_BODY="❌ Some Jest tests failed. Please check the logs and fix the issues before merging.\n\n**Failed Tests:**\n\n\`\`\`\n$(echo "$FAILED_TESTS" | sed 's/^/    /')\n\`\`\`"
          fi

          echo "$COMMENT_BODY" | gh pr comment ${{ steps.results.outputs.PR_NUMBER }} --body-file -
