name: Run Jest Tests on PR

on:
  pull_request:

jobs:
  test:
    name: Run Jest Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write  # Keep only if needed

    steps:
      - name: Checkout Repository
        uses: actions/checkout@<SHA>

      - name: Setup Node.js
        uses: actions/setup-node@<SHA>
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Run Jest Tests
        id: jest
        run: |
          npm test -- --json --outputFile=jest-results.json || echo "TESTS_FAILED=true" >> $GITHUB_ENV

      - name: Read Jest Results
        id: results
        run: |
          if [ -z "$TESTS_FAILED" ]; then
            TESTS_FAILED=false
          fi

          if [ "$TESTS_FAILED" = "true" ]; then
            TESTS_PASSED=false
            echo "TESTS_PASSED=false" >> $GITHUB_ENV
            FAILED_TESTS=$(jq -r '[.testResults[] | select(.status == "failed") | .name] | map(split("/") | last) | join("\n")' jest-results.json || echo "Parsing error")
            echo "FAILED_TESTS<<EOF" >> $GITHUB_ENV
            echo "$FAILED_TESTS" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
          else
            TESTS_PASSED=true
            echo "TESTS_PASSED=true" >> $GITHUB_ENV
            echo "FAILED_TESTS=None" >> $GITHUB_ENV
          fi

          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH" || echo "0")

          COMMENT_FILE=$(mktemp)

          {
            if [ "$TESTS_PASSED" = "true" ]; then
              echo "✅ All Jest tests passed! This PR is ready to merge."
            else
              echo "❌ Some Jest tests failed. Please check the logs and fix the issues before merging."
              echo ""
              echo "**Failed Tests:**"
              echo ""
              echo '```'
              echo "$FAILED_TESTS"
              echo '```'
            fi
          } > "$COMMENT_FILE"

      - name: Post PR Comment using gh CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "$PR_NUMBER" != "0" ]; then
            gh pr comment "$PR_NUMBER" --body-file "${{ steps.results.outputs.COMMENT_FILE }}"
          fi
